[package]
name = "rusttyper"
version = "0.3.0"
authors = ["neptunepink <purpleposeidon@gmail.com>"]
license = "MIT / Apache-2.0"
description = "Basic text layout, using rusttype."
repository = "https://github.com/purpleposeidon/rusttyper"

[dependencies]
rusttype = "^0.2.3"
glium = "^0.24"
unicode-normalization = "^0.1.2"
